import Head from 'next/head'
import { signIn } from 'next-auth/react'


function SignIn() {
    return (
        <div className="bg-black flex flex-wrap-reverse md:flex-row md:flex-nowrap">

            <Head>
                <title>Sign In</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <img src = "https://abs.twimg.com/sticky/illustrations/lohp_en_1302x955.png" className="min-h-screen w-[100%] md:w-1/2"></img>

            <div className="text-white m-10 space-y-20 basis-1/2">
                <img src = "https://icon-library.com/images/twitter-icon-white/twitter-icon-white-9.jpg" className="w-20 h-20"></img>
                <h1 className="text-6xl font-semibold">Happening now</h1>
                <h3 className="text-3xl font-semibold">Join Twitter Today</h3>
                <button className="py-4 px-10 bg-white text-black rounded-xl font-semibold" onClick = {() => signIn('google', { callbackUrl: '/' })}>Sign in with Google</button>
            </div>
        </div>
    )
}

export default SignIn;

